version: '3.9'
services:
  mongodb:
    container_name: taotip-mongodb
    image: mongo:5.0.8
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword

    ports:
      - 27017:27017
    networks:
      - backend
    volumes:
      - mongodb_data_container:/data/db
      - ./mongodb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  taotip:
    container_name: taotip
    build:
      context: ./taotip/
      dockerfile: Dockerfile
    volumes:
      - taotip_data_container:/data/taotip
    depends_on:
      - mongodb
    networks:
      - backend
  export-service:
    container_name: export-service
    build:
      context: ./taotip-export/
      dockerfile: Dockerfile
    ports:
      - 80:5000
    depends_on:
      - mongodb
    networks:
      - backend
    
volumes:
  mongodb_data_container:
  taotip_data_container:

networks:
  backend:
    driver: bridge
