version: '3.9'
services:
  mongodb:
    container_name: taotip-mongodb
    image: mongo:5.0.8
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    networks:
      - backend
    volumes:
      - mongodb_data_container:/data/db
      - ./mongodb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  taotip:
    container_name: taotip
    restart: always
    build:
      context: ./taotip/
      dockerfile: Dockerfile
    volumes:
      - taotip_data_container:/data/taotip
    depends_on:
      - mongodb
    networks:
      - backend
  export-service:
    container_name: export-service
    restart: always
    build:
      context: ./taotip-export/
      dockerfile: Dockerfile
    depends_on:
      - mongodb
    networks:
      - backend

  nginx:
    image: nginx:1.15-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - backend
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    restart: on-failure[:2] # restart on failure, max 2 times
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    
volumes:
  mongodb_data_container:
  taotip_data_container:

networks:
  backend:
    driver: bridge
