version: '3.9'
services:
  mongodb_container:
    container_name: container-mongodb
    image: mongo:5.0.8
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword

    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
  taotip:
    container_name: taotip
    build:
      dockerfile: Dockerfile
    volumes:
      - taotip_data_container:/data/taotip
    depends_on:
      - mongodb_container
      - ./mongodb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

volumes:
  mongodb_data_container:
  taotip_data_container:
