version: '3.9'
services:
  mongodb:
    container_name: container-mongodb
    image: mongo:5.0.8
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword

    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
      - ./mongodb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  taotip:
    container_name: taotip
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - taotip_data_container:/data/taotip
    depends_on:
      - mongodb
  backend:
    container_name: backend
    build:
      context: ./taotip-export/backend
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - mongodb
  frontend:
    container_name: frontend
    build:
      context: ./taotip-export/frontend
      dockerfile: Dockerfile
    ports:
      - 80:3000
    depends_on:
      - backend
    
volumes:
  mongodb_data_container:
  taotip_data_container:
